### ISSUE TITLE
抓包获取PeerID和devicesign后上行加速还是失效。

### ISSUE THREAD

**Issue by Iy204** [sensec/luci-app-xlnetacc#1]
还是无法登录
抓取到的数据
{"protocolVersion":"200","sequenceNo":"1000001","platformVersion":"2","isCompressed":"0","businessType":"68","clientVersion":"2.4.1.3","peerID":"16个字符","appName":"ANDROID-com.xunlei.vip.swjsq","sdkVersion":"177662","devicesign":"div101.65个字符","deviceModel":"MX4","deviceName":"Meizu Mx4","OSVersion":"6.0.1","userName":"帐号","passWord":"密码","verifyKey":"","verifyCode":""}

脚本的详细日志

2018/01/23 08:48:52 acc_ipaddr is X
2018/01/23 08:48:52 绑定IP地址: X
2018/01/23 08:48:52 _http_cmd is wget-ssl -nv -t 1 -O - --no-check-certificate --compression=gzip --bind-address=27.153.229.57
2018/01/23 08:48:53 ret is 
2018/01/23 08:48:53 _userid is 
2018/01/23 08:48:53 _sessionid is 
2018/01/23 08:48:53 帐号登录失败。错误代码: -1
2018/01/23 08:55:00 trap sigterm, exit

**Comment by sensec** [comment]
div101.后面是64个字符（两个MD5值），你抄错了。。。
根据lphgor兄的提示，devicesign算法已经有了，也就是说不用再抓包获取。新版本正在制作，请稍等。

**Comment by sensec** [comment]
新版本1.0.3.2已释出，不再需要抓包，请试用。

**Comment by Iy204** [comment]
还是无法加速成功。
2018/01/23 13:46:08 ------------------------------
2018/01/23 13:46:08 迅雷快鸟正在启动...
2018/01/23 13:46:08 down_acc is 0
2018/01/23 13:46:08 up_acc is 1
2018/01/23 13:46:08 network is wan
2018/01/23 13:46:08 username is X
2018/01/23 13:46:08 _peerid is x
2018/01/23 13:46:09 _devicesign is div101.x
2018/01/23 13:46:09 acc_ipaddr is 
2018/01/23 13:46:09 获取网络 wan IP地址出错
2018/01/23 13:46:14 acc_ipaddr is 
2018/01/23 13:46:14 获取网络 wan IP地址出错
2018/01/23 13:46:19 acc_ipaddr is 27.159.203.71
2018/01/23 13:46:19 绑定IP地址: 27.159.203.71
2018/01/23 13:46:19 _http_cmd is wget-ssl -nv -t 1 -O - --no-check-certificate --compression=gzip --bind-address=27.159.203.71
2018/01/23 13:46:20 ret is 
2018/01/23 13:46:20 _userid is 
2018/01/23 13:46:20 _sessionid is 
2018/01/23 13:46:20 帐号登录失败。错误代码: -1

迅雷安全中心也看不到登录记录
难道是因为我只购买了上行会员的原因？

**Comment by dt743** [comment]
@Iy204 和你一模一样的情况，日志就不上了

**Comment by sensec** [comment]
帐号登录失败。错误代码: -1
日志出现这个说明向迅雷服务器发送了帐号登录命令后，服务器没有返回任何数据，一般来说是服务器抽风了。无需理会，等待3分钟后会重试的。
下个版本我会改成等待5秒。
