### ISSUE TITLE
出现验证码能解吗？

### ISSUE THREAD

**Issue by daofeng2015** [sensec/luci-app-xlnetacc#2]
系统日志：
Wed Jan 24 22:03:16 2018 daemon.notice xlnetacc: XLNetAcc is starting ...
Wed Jan 24 22:25:28 2018 daemon.notice xlnetacc: XLNetAcc has stoped.
Wed Jan 24 22:25:29 2018 daemon.notice xlnetacc: XLNetAcc is starting ...
Wed Jan 24 22:25:57 2018 daemon.notice xlnetacc: XLNetAcc has stoped.
Wed Jan 24 22:25:59 2018 daemon.notice xlnetacc: XLNetAcc is starting ...
Wed Jan 24 22:37:46 2018 daemon.notice xlnetacc: XLNetAcc has stoped.
Wed Jan 24 22:37:47 2018 daemon.notice xlnetacc: XLNetAcc is starting ...

日志文件：
2018/01/24 22:03:17 ------------------------------
2018/01/24 22:03:17 迅雷快鸟正在启动...
2018/01/24 22:03:18 绑定IP地址: 221.234.*.81
2018/01/24 22:03:18 帐号登录失败。错误代码: 6，原因: 为了您的账号安全，请输入验证码[6]
2018/01/24 22:25:29 ------------------------------
2018/01/24 22:25:29 迅雷快鸟正在启动...
2018/01/24 22:25:30 绑定IP地址: 221.234.*.81
2018/01/24 22:25:30 帐号登录失败。错误代码: 6，原因: 为了您的账号安全，请输入验证码[6]
2018/01/24 22:25:59 ------------------------------
2018/01/24 22:25:59 迅雷快鸟正在启动...
2018/01/24 22:25:59 绑定IP地址: 221.234.*.81
2018/01/24 22:25:59 帐号登录失败。错误代码: 6，原因: 为了您的账号安全，请输入验证码[6]
2018/01/24 22:37:47 ------------------------------
2018/01/24 22:37:47 迅雷快鸟正在启动...
2018/01/24 22:37:47 down_acc is 1
2018/01/24 22:37:47 up_acc is 0
2018/01/24 22:37:47 network is wan
2018/01/24 22:37:47 username is 1*******
2018/01/24 22:37:47 _peerid is ************004V
2018/01/24 22:37:47 _devicesign is div101.**********8822543874959ae609fadd8353139210f8e591c996b2c09d460008
2018/01/24 22:37:47 _bind_ip is 221.234.*.*
2018/01/24 22:37:47 绑定IP地址: 221.234.*.*
2018/01/24 22:37:47 _http_cmd is wget-ssl -nv -t 1 -O - --no-check-certificate --compression=gzip --bind-address=221.234.*.81
2018/01/24 22:37:48 ret is {"platformVersion":"2","errorCode":"6","errorDescUrl":"http:\/\/verify2.xunlei.com\/image?t=MEA","isCompressed":"0","errorDesc":"为了您的账号安全，请输入验证码[6]","protocolVersion":"200","verifyType":"MEA","errorIsRetry":0,"msgurl":"","isequenceNo":"1000001"}
2018/01/24 22:37:48 _userid is 
2018/01/24 22:37:48 _sessionid is 
2018/01/24 22:37:48 帐号登录失败。错误代码: 6，原因: 为了您的账号安全，请输入验证码[6]

**Comment by sensec** [comment]
不打算加入验证码识别。原因有二：一是纯shell实现，由于验证码识别涉及到大量图形处理必然需要调用外部工具，依赖过多不利于普遍使用，而且也会增加代码复杂度。二是根据反馈信息，迅雷目前的机制是出现验证码后等待2小时以上再登录就OK，所以目前的处理方式就是等待130分钟后重新尝试登录，无需人工干预。

**Comment by daofeng2015** [comment]
然而我从昨天晚上等到今天10点还是提升这个

**Comment by sensec** [comment]
不要尝试频繁重启xlnetacc。你可以试试关了luci-app-xlnetacc，等上2小时然后用手机APP登录一次，注销后再等一段时间再重新打开luci-app-xlnetacc。还不行的话只能联系迅雷客服了。

**Comment by sensec** [comment]
如果一直出现要求输入验证码，可以先去迅雷网站改密码，然后重新设置插件再重启就好。
原因是同一个密码重试过多后被迅雷判定异常，列入了风控表。
