### ISSUE TITLE
无法提速，迅雷快鸟已停止

### ISSUE THREAD

**Issue by tonyliangli** [sensec/luci-app-xlnetacc#3]
请问这是什么情况，超级会员，电脑，手机客户端提速正常。
系统日志：
Sat Jan 27 01:25:03 2018 daemon.notice xlnetacc: XLNetAcc is starting ...
Sat Jan 27 01:26:02 2018 daemon.notice xlnetacc: XLNetAcc is starting ...
Sat Jan 27 01:42:51 2018 daemon.notice xlnetacc: XLNetAcc is starting ...
Sat Jan 27 01:43:21 2018 daemon.notice xlnetacc: XLNetAcc is starting ...

日志文件：
2018/01/27 01:25:03 迅雷快鸟正在启动...
2018/01/27 01:25:04 绑定IP地址: 111.201.64.29
2018/01/27 01:25:04 帐号登录成功
2018/01/27 01:25:38 下行提速会员无效或已到期。
2018/01/27 01:25:38 帐号注销成功
2018/01/27 01:25:38 无法提速，迅雷快鸟已停止。
2018/01/27 01:26:02 ------------------------------
2018/01/27 01:26:02 迅雷快鸟正在启动...
2018/01/27 01:26:03 绑定IP地址: 111.201.64.29
2018/01/27 01:26:03 帐号登录成功
2018/01/27 01:26:04 下行提速会员无效或已到期。
2018/01/27 01:26:04 帐号注销成功
2018/01/27 01:26:04 无法提速，迅雷快鸟已停止。
2018/01/27 01:42:51 ------------------------------
2018/01/27 01:42:51 迅雷快鸟正在启动...
2018/01/27 01:42:51 绑定IP地址: 111.201.64.29
2018/01/27 01:42:51 帐号登录成功
2018/01/27 01:42:52 下行提速会员无效或已到期。
2018/01/27 01:42:52 帐号注销成功
2018/01/27 01:42:52 无法提速，迅雷快鸟已停止。
2018/01/27 01:43:21 ------------------------------
2018/01/27 01:43:21 迅雷快鸟正在启动...
2018/01/27 01:43:21 _peerid is D8C8E99771E4004V
2018/01/27 01:43:21 _devicesign is div101.2888cb0c9a936da2a3744155874ffe7b5723165f5bea4d42e3f6fbc19c242956
2018/01/27 01:43:21 _bind_ip is 111.201.64.29
2018/01/27 01:43:21 绑定IP地址: 111.201.64.29
2018/01/27 01:43:21 _http_cmd is wget-ssl -nv -t 1 -O - --no-check-certificate --compression=gzip --bind-address=111.201.64.29
2018/01/27 01:43:21 ret is {"timestamp":"1516988601","userNewNo":"6510966","platformVersion":"2","errorCode":"0","vipList":[{"isVip":"1","isYear":"0","vipLevel":"7","vipGrow":"44694","expireDate":"20200325","payName":"网银支付方式","vasType":"5","vasid":"2","payId":"4"}],"userID":"20749025","secureKey":"sk100.767bb8f415b9f3199a610899730ddc11","isCompressed":"0","sessionID":"D02F6590837573E9D6F99D3EFDF1342B","loginKey":"lk10.89fade9b125181c83576bbd054417a6796c0e08ea2238d393e78cdf9543797560c60df8bfcc886bf8efe385c1aa66c25","userName":"tonyliangli","nickName":"Knight","sequenceNo":"1000001","account":"161008","protocolVersion":"200"}
2018/01/27 01:43:21 _userid is 20749025
2018/01/27 01:43:21 _sessionid is D02F6590837573E9D6F99D3EFDF1342B
2018/01/27 01:43:21 帐号登录成功
2018/01/27 01:43:22 ret is {"birthday":"19920924","platformVersion":"2","role":"0","order":"65758","rank":"55","sequenceNo":"1000002","vipList":[{"isVip":"1","isAutoDeduct":"0","isYear":"0","register":"20100514","vipLevel":"7","vipGrow":"44694","expireDate":"20200325","payName":"网银支付方式","vasType":"5","vasid":"2","isRemind":"0","vipDayGrow":"15","payId":"4"},{"isVip":"0","isAutoDeduct":"0","isYear":"0","vipLevel":"0","vipGrow":"0","expireDate":"----","payName":"----","vasType":"0","vasid":"14","isRemind":"0","vipDayGrow":"0","payId":"0"}],"userNewNo":"6510966","province":"北京市","mobile":"176****3536","isSubAccount":"0","errorCode":"0","sex":"m","isSpecialNum":"0","userID":"20749025","todayScore":"0","isCompressed":"0","personalSign":"","city":"北京市","protocolVersion":"200","country":"中华人民共和国","nickName":"Knight","account":"161008","imgURL":"http:\/\/img2.user.kanimg.com\/usrimg\/20749025\/default\/1420041600\/%s"}
2018/01/27 01:43:22 下行提速会员无效或已到期。
2018/01/27 01:43:22 ret is {"isCompressed":"0","platformVersion":"2","protocolVersion":"200","sequenceNo":"1000003","userID":"20749025","errorCode":"0"}
2018/01/27 01:43:22 帐号注销成功
2018/01/27 01:43:22 无法提速，迅雷快鸟已停止。

**Comment by sensec** [comment]
https://github.com/sensec/luci-app-xlnetacc/tree/94391fdadd4ffbd9597797c2ac99f62609b1746a
请测试。迅雷超级会员支持上行提速吗？

**Comment by tonyliangli** [comment]
您好，也是不支持的：

2018/01/27 10:35:26 ------------------------------
2018/01/27 10:35:26 迅雷快鸟正在启动...
2018/01/27 10:35:26 _peerid is D8C8E99771E4004V
2018/01/27 10:35:26 _devicesign is div101.2888cb0c9a936da2a3744155874ffe7b5723165f5bea4d42e3f6fbc19c242956
2018/01/27 10:35:26 _bind_ip is 111.201.64.29
2018/01/27 10:35:26 绑定IP地址: 111.201.64.29
2018/01/27 10:35:26 _http_cmd is wget-ssl -nv -t 1 -O - --no-check-certificate --compression=gzip --bind-address=111.201.64.29
2018/01/27 10:35:27 ret is {"timestamp":"1517020527","userNewNo":"6510966","platformVersion":"2","errorCode":"0","vipList":[{"isVip":"1","isYear":"0","vipLevel":"7","vipGrow":"44694","expireDate":"20200325","payName":"网银支付方式","vasType":"5","vasid":"2","payId":"4"}],"userID":"20749025","secureKey":"sk100.767bb8f415b9f3199a610899730ddc11","isCompressed":"0","sessionID":"71D711FF9444A71AB233673F528B3CB1","loginKey":"lk10.feb8bbe81d6023bf3cb0298e72d2d99496c0e08ea2238d393e78cdf9543797560c60df8bfcc886bf8efe385c1aa66c25","userName":"tonyliangli","nickName":"Knight","sequenceNo":"1000001","account":"161008","protocolVersion":"200"}
2018/01/27 10:35:27 _userid is 20749025
2018/01/27 10:35:27 _sessionid is 71D711FF9444A71AB233673F528B3CB1
2018/01/27 10:35:27 帐号登录成功
2018/01/27 10:35:27 ret is {"birthday":"19920924","platformVersion":"2","role":"0","order":"65758","rank":"55","sequenceNo":"1000002","vipList":[{"isVip":"1","isAutoDeduct":"0","isYear":"0","register":"20100514","vipLevel":"7","vipGrow":"44694","expireDate":"20200325","payName":"网银支付方式","vasType":"5","vasid":"2","isRemind":"0","vipDayGrow":"15","payId":"4"},{"isVip":"0","isAutoDeduct":"0","isYear":"0","vipLevel":"0","vipGrow":"0","expireDate":"----","payName":"----","vasType":"0","vasid":"14","isRemind":"0","vipDayGrow":"0","payId":"0"}],"userNewNo":"6510966","province":"北京市","mobile":"176****3536","isSubAccount":"0","errorCode":"0","sex":"m","isSpecialNum":"0","userID":"20749025","todayScore":"0","isCompressed":"0","personalSign":"","city":"北京市","protocolVersion":"200","country":"中华人民共和国","nickName":"Knight","account":"161008","imgURL":"http:\/\/img2.user.kanimg.com\/usrimg\/20749025\/default\/1420041600\/%s"}
2018/01/27 10:35:27 下行提速会员无效或已到期。
2018/01/27 10:35:28 ret is {"birthday":"19920924","platformVersion":"2","role":"0","order":"65758","rank":"55","sequenceNo":"1000003","vipList":[{"isVip":"1","isAutoDeduct":"0","isYear":"0","register":"20100514","vipLevel":"7","vipGrow":"44694","expireDate":"20200325","payName":"网银支付方式","vasType":"5","vasid":"2","isRemind":"0","vipDayGrow":"15","payId":"4"},{"isVip":"0","isAutoDeduct":"0","vipLevel":"0","vipGrow":"0","expireDate":"----","payName":"----","vasType":"0","vasid":"33","isRemind":"0","vipDayGrow":"0","payId":"0"}],"userNewNo":"6510966","province":"北京市","mobile":"176****3536","isSubAccount":"0","errorCode":"0","sex":"m","isSpecialNum":"0","userID":"20749025","todayScore":"0","isCompressed":"0","personalSign":"","city":"北京市","protocolVersion":"200","country":"中华人民共和国","nickName":"Knight","account":"161008","imgURL":"http:\/\/img2.user.kanimg.com\/usrimg\/20749025\/default\/1420041600\/%s"}
2018/01/27 10:35:28 上行提速会员无效或已到期。
2018/01/27 10:35:28 ret is {"isCompressed":"0","platformVersion":"2","protocolVersion":"200","sequenceNo":"1000004","userID":"20749025","errorCode":"0"}
2018/01/27 10:35:28 帐号注销成功
2018/01/27 10:35:28 无法提速，迅雷快鸟已停止。

**Comment by tonyliangli** [comment]
超级会员本身也是不支持上行提速的。

**Comment by sensec** [comment]
https://raw.githubusercontent.com/sensec/luci-app-xlnetacc/test-200/files/root/usr/bin/xlnetacc.sh
下载这个文件，替换 /usr/bin/xlnetacc.sh，然后重启快鸟。

**Comment by tonyliangli** [comment]
可以用了，十分感谢！
