### ISSUE TITLE
下行提速突然无效，显示“下行提速成功，带宽已从 4M 提升到 0M”

### ISSUE THREAD

**Issue by KatyushaScarlet** [sensec/luci-app-xlnetacc#7]
这个问题是今天晚上突然发现的，之前使用了3天都很稳定。
已做出过如下尝试，但依然提速无效：
1.重启路由器
2.卸载插件后重新安装
3.停止插件，手动开启迅雷快鸟，显示“已从安卓版发起提速”，但依然无效果
4.重刷路由器，重新安装插件

环境：
湖北电信校园网（4M），pppoe拨号上网
斐讯K2路由器，刷入 OpenWrt Chaos Calmer 15.05.1

系统日志：
2018/03/29 20:59:48 迅雷快鸟正在启动...
2018/03/29 20:59:48 绑定IP地址: 10.50.90.124
2018/03/29 20:59:48 帐号登录成功
2018/03/29 20:59:49 获取下行提速会员信息成功。会员到期时间：2018-04-23
2018/03/29 20:59:49 获取下行提速入口成功。运营商：湖北电信
2018/03/29 20:59:50 下行可以提速。当前带宽 4M，可提升至 100M
2018/03/29 20:59:50 下行提速成功，带宽已从 4M 提升到 0M

请问是否需要提供更详细的日志或使用情况？

**Comment by KatyushaScarlet** [comment]
注：本IP为校园网内网IP

**Comment by sensec** [comment]
用迅雷快鸟客户端能提速吗？
最好是开启详细日志后贴一下，我看看服务器返回了什么数据。

**Comment by sensec** [comment]
另外你可以尝试一下去迅雷网站改密码，然后重启应用。

**Comment by KatyushaScarlet** [comment]
请问详细日志里是否会包含我的隐私信息？
如果不包含，我就贴上来

**Comment by KatyushaScarlet** [comment]
现在发现，仅仅是运行快鸟客户端也无法提速了。
需要先点击上传提速试用，然后点击下载提速，再启用路由器提速并退出快鸟，才能真正提速。
但上传试用的机会不是一直都有，所以有些不方便。
在使用这个路由器插件之前，一切都是正常的

**Comment by sensec** [comment]
详细日志包含了迅雷服务器返回信息，里面可能有你的帐号、ID、接入商、到期日期等私人信息，你可以用*号代替再发上来。
这种情况你是第一个报告的，所以我也无法给出更多建议。你可以试试只用迅雷客户端，测试几天看看有没有什么异常。或者联系迅雷客服寻求帮助（不过估计很难有结果。快鸟涉及到迅雷和接入商，从你说的情况看，问题应该出在湖北电信那里，这样迅雷也没什么办法）。

**Comment by KatyushaScarlet** [comment]
系统日志：
Mon Apr  2 16:35:52 2018 daemon.notice xlnetacc: XLNetAcc is starting ...
日志文件：
2018/04/02 16:35:52 迅雷快鸟正在启动...
2018/04/02 16:35:52 _peerid is D14E130C6423004V
2018/04/02 16:35:52 _devicesign is div101.0be10d2b858b237a662238c735611714a8582668aa8d2a5b23e1415291e27e5a
2018/04/02 16:35:52 绑定IP地址: 10.50.112.180
2018/04/02 16:35:53 login is {"timestamp":"1522658152","userNewNo":"*********","platformVersion":"2","errorCode":"0","vipList":[{"isVip":"0","isYear":"0","vipLevel":"4","vipGrow":"4853","expireDate":"20180111","payName":"商务合作付费","vasType":"3","vasid":"2","payId":"801"}],"userID":"170661035","secureKey":"sk100.d747f3163c5f6cb1c715e593d1df0f70","isCompressed":"0","sessionID":"1C55206ACD09562EC2C99AADF07096A9","loginKey":"lk10.5667805e64abb9de00207f0f55d11f0c9b2208f19fcc7900e2a136f7953217f305116ee36fab83e086d2d67006729b4b","userName":"","nickName":"Katyusha","sequenceNo":"1000001","account":"38727","protocolVersion":"200"}
2018/04/02 16:35:53 _sessionid is 1C55206ACD09562EC2C99AADF07096A9
2018/04/02 16:35:53 帐号登录成功
2018/04/02 16:35:53 getuserinfo 1 is {"birthday":"","platformVersion":"2","role":"0","order":"2551318","rank":"26","sequenceNo":"1000002","vipList":[{"isVip":"0","isAutoDeduct":"0","isYear":"0","register":"20111027","vipLevel":"4","vipGrow":"4853","expireDate":"20180111","payName":"商务合作付费","vasType":"3","vasid":"2","isRemind":"0","vipDayGrow":"10","payId":"801"},{"isVip":"1","isAutoDeduct":"0","isYear":"0","vipLevel":"1","vipGrow":"0","expireDate":"20180423","payName":"网银支付方式","vasType":"3","vasid":"14","isRemind":"0","vipDayGrow":"12","payId":"4"}],"userNewNo":"*********","province":"","mobile":"177****2090","isSubAccount":"0","errorCode":"0","sex":"f","isSpecialNum":"0","userID":"170661035","todayScore":"25","isCompressed":"0","personalSign":"","city":"","protocolVersion":"200","country":"","nickName":"Katyusha","account":"38727","imgURL":"http:\/\/img2.user.kanimg.com\/usrimg\/170661035\/default\/1420041600\/%s"}
2018/04/02 16:35:53 获取下行提速会员信息成功。会员到期时间：2018-04-23
2018/04/02 16:35:54 getuserinfo 2 is {"birthday":"","platformVersion":"2","role":"0","order":"2551318","rank":"26","sequenceNo":"1000003","vipList":[{"isVip":"0","isAutoDeduct":"0","isYear":"0","register":"20111027","vipLevel":"4","vipGrow":"4853","expireDate":"20180111","payName":"商务合作付费","vasType":"3","vasid":"2","isRemind":"0","vipDayGrow":"10","payId":"801"},{"isVip":"0","isAutoDeduct":"0","vipLevel":"0","vipGrow":"0","expireDate":"----","payName":"----","vasType":"0","vasid":"33","isRemind":"0","vipDayGrow":"0","payId":"0"}],"userNewNo":"*********","province":"","mobile":"177****2090","isSubAccount":"0","errorCode":"0","sex":"f","isSpecialNum":"0","userID":"170661035","todayScore":"25","isCompressed":"0","personalSign":"","city":"","protocolVersion":"200","country":"","nickName":"Katyusha","account":"38727","imgURL":"http:\/\/img2.user.kanimg.com\/usrimg\/170661035\/default\/1420041600\/%s"}
2018/04/02 16:35:54 上行提速会员无效或已到期
2018/04/02 16:35:54 portal 1 is {"errno":0,"interface_ip":"119.147.41.210","interface_port":"12180","message":"","province":"hu_bei","province_name":"湖北","sp":"tel","sp_name":"电信"}
2018/04/02 16:35:54 _portal_down is http://119.147.41.210:12180/v2
2018/04/02 16:35:54 获取下行提速入口成功。运营商：湖北电信
2018/04/02 16:35:54 bandwidth 1 is {"auto_backend_supported":0,"bandwidth":{"downstream":4096,"upstream":4096},"bind_dial_account":"","can_upgrade":1,"can_upspeedup":1,"dial_account":"hb::a17720010","errno":0,"max_bandwidth":{"downstream":102400,"upstream":10240},"message":"","province":"hu_bei","province_name":"湖北","richmessage":"","sequence":253776360,"sp":"tel","sp_name":"电信","timestamp":1522658153}
2018/04/02 16:35:54 _cur_down is 4
2018/04/02 16:35:54 _dial_account is hb::a17720010
2018/04/02 16:35:54 下行可以提速。当前带宽 4M，可提升至 100M
2018/04/02 16:35:54 upgrade 1 is {"button_data":{"can_click":0,"can_click_time":0,"link_url":"","name":"","on_click_type":0},"errno":812,"hover_bubble":"","is_button":0,"is_text":0,"message":"speedup server already speed up","richmessage":"当前宽带已处于提速状态","sequence":253776361,"timestamp":1522658153}
2018/04/02 16:35:54 下行提速成功，带宽已从 4M 提升到 0M

**Comment by sensec** [comment]
返回是812，已处于提速状态。这一般是局域网内某个快鸟客户端正在运行，或者没有正常退出。检查一下吧，不要同时运行多个客户端，容易被服务器认定为异常的。

**Comment by KatyushaScarlet** [comment]
我的局域网内确实没有第二个客户端在同时运行，并且出现该错误时，宽带也没有提速

**Comment by oit63** [comment]
@KatyushaScarlet 
你可以参考我的回答
https://github.com/fffonion/Xunlei-Fastdick/issues/73
