### ISSUE TITLE
日志显示错误

### ISSUE THREAD

**Issue by fanck0605** [sensec/luci-app-xlnetacc#8]
_2018/06/22 16:48:34 迅雷快鸟正在启动...
2018/06/22 16:48:34 绑定IP地址: 192.168.1.10
2018/06/22 16:48:34 帐号登录成功
2018/06/22 16:48:34 迅雷超级会员有效。会员到期时间：2018-07-22
2018/06/22 16:48:34 迅雷快鸟会员有效。会员到期时间：2018-07-22
2018/06/22 16:48:34 更新登录时间成功。帐号登录展期：2018-07-22
2018/06/22 16:48:34 获取下行提速入口成功。运营商：江苏电信
2018/06/22 16:48:35 下行可以提速。当前带宽 60M，可提升至 100M
2018/06/22 16:48:36 下行提速成功，带宽已提升到 0M_

实际已经提速成功，测速100M正常
最近才出现的问题，前些天还是提示提速到100Mbps

同#7

**Comment by fanck0605** [comment]
这可能是一个由超级会员引起的BUG，最近对账号的操作就是充值了一个超级会员！！

**Comment by sensec** [comment]
方便提供一下详细日志吗？“下行提速成功，带宽已提升到 0M”之前的一行，“upgrade 1 is ...”，需要看一下服务器返回值。

**Comment by fanck0605** [comment]
不好意思啊。正好最近两天，苏州电信免费给我提速到了100M，快鸟用不了。只有提速错误的日志了。。

**Comment by sensec** [comment]
收到，恭喜达成免费提速成就。
日志我先删了，以免含有私人信息。

**Comment by fanck0605** [comment]
哈哈，谢谢。
